version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#     networks:
#       - my_network

#   backend:
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     container_name: backend
#     ports:
#       - "${BACKEND_PORT}:${BACKEND_PORT}"
#     depends_on: 
#       - db
#     environment:
#       - BACKEND_PORT=${BACKEND_PORT}
#     networks:
#       - my_network

# networks:
#   my_network:
#     driver: bridge
